default:
  datawarehouse:
    driver: 'ODBC Driver 17 for SQL Server' 
    server: 'dsarforecast.database.windows.net'
    uid: 'dsarforecast_master'
    pwd: 'OB9WqaiHhrWxZMhpXQO0'  
    port: 1433
    database: 'dsarforecast'
